### ISSUE TITLE
[Extra Chat] Unable to Register Character

### ISSUE THREAD

**Issue by k0k0b** [lojewalo/plugin-issues#100]
After installing the plugin for the first time I try to register my character, it says "Retrieving Challenge" and "Waiting", and then returns back to the "Register Character" screen and I can no longer click on any of the buttons to try to register again. I tried turning the plug in off and on and tried and register again which did not work, I also tried to uninstall and reinstall the plugin which also did not work facing the same issue :( 

I started trying a few months ago now, and give it another test every week to see if there's any change but unfortunately nothing. I'm really not sure what else to do, and I know there are some other people with the same issue. 

I would love to be able to join my friends chat if there's anything you could do to help, I very much appreciate your time thank you <3

I've attached some screenshots of the issue:
![1](https://github.com/lojewalo/plugin-issues/assets/156914719/8af9eb72-8af7-457e-9566-ecae08dff3fb)
![2](https://github.com/lojewalo/plugin-issues/assets/156914719/59dc8e67-7d38-4ae0-ad9e-aad1c08e41b4)
![3](https://github.com/lojewalo/plugin-issues/assets/156914719/b0ec515f-063d-4323-98f8-bdb4b6fb89eb)
![4](https://github.com/lojewalo/plugin-issues/assets/156914719/12790592-b71f-40bb-a435-bbbae4b9b868)

**Comment by lojewalo** [comment]
What server is your character on when you try, and what is their home world?

**Comment by lojewalo** [comment]
Okay, never mind, I found the world in the server logs. The problem here is that Square Enix's [search on the Lodestone](https://na.finalfantasyxiv.com/lodestone/character/?q=Koko+Kok&worldname=Adamantoise) fails miserably for your name. I'll have to investigate this.

**Comment by Pyresque** [comment]
Hi, sorry for commenting on an old issue, but I'm having the exact problem right now. I already had an account though, but recently had to do a clean reinstall of everything on my new PC, and upon trying to authenticate on ExtraChat I have the same issue as OP. As in, after clicking "Register [Character Name]" it says "Retrieving Challenge" and "Waiting", and then returns back to the "Register Character" screen and I can no longer click on any of the buttons to try to register again.

This is what shows on my Dalamud log when the issue happens:

```
16:57:13.508 | ERR | [ExtraChat] Error in client loop
	System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
	 ---> System.IO.IOException: Unable to read data from the transport connection: A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo..
	 ---> System.Net.Sockets.SocketException (995): A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo.
	   --- End of inner exception stack trace ---
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
	--- End of stack trace from previous location ---
	   at ExtraChat.Ext.ReceiveMessage(ClientWebSocket client) in /work/repo/client/ExtraChat/Ext.cs:line 24
	   at ExtraChat.Client.Loop() in /work/repo/client/ExtraChat/Client.cs:line 588
	   at ExtraChat.Client.<StartLoop>b__43_0() in /work/repo/client/ExtraChat/Client.cs:line 98
16:57:14.509 | INF | [LOCALPLUGIN] Finished unloading "ExtraChat"
16:57:14.509 | INF | [LOCALPLUGIN] Loading ExtraChat.dll
16:57:14.728 | INF | [LOCALPLUGIN] Finished loading "ExtraChat"
16:57:18.457 | ERR | [ExtraChat] Error in client loop
	System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
	   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
	   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
	--- End of stack trace from previous location ---
	   at ExtraChat.Ext.ReceiveMessage(ClientWebSocket client) in /work/repo/client/ExtraChat/Ext.cs:line 24
	   at ExtraChat.Client.Loop() in /work/repo/client/ExtraChat/Client.cs:line 588
	   at ExtraChat.Client.<StartLoop>b__43_0() in /work/repo/client/ExtraChat/Client.cs:line 98
```

My character's home world is Golem, on Dynamis. Is this maybe an issue with being on one of the four new Dynamis worlds?
